version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instapp-api
    ports:
      - '3000:3000'
    env_file: docker-compose.env
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: unless-stopped

  # db:
  #   image: postgres:15
  #   container_name: instapp-db
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_DATABASE}
  #   env_file:
  #     - .env.docker
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  postgres_data:
