#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting on staged files
npx lint-staged

# Check for security vulnerabilities
npm audit --audit-level=moderate

# Run fast tests that are relevant to changed files
npm test -- --passWithNoTests --findRelatedTests $(git diff --staged --name-only)